BEGIN;

DROP TABLE IF EXISTS USERS , URLS CASCADE;

CREATE TABLE IF NOT EXISTS USERS (
    NAME VARCHAR(25) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS URLS (
    SHORT_URL TEXT PRIMARY KEY,
    USER_NAME VARCHAR(25) REFERENCES USERS(name) ON UPDATE CASCADE,
    LONG_URL TEXT NOT NULL
);

COMMIT;